# Generated by Django 6.1 on 2026-08-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GitHub 아이디'),
        ),
    ]
