# Generated by Django 6.1 on 2026-08-09 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='수업 날짜')),
                ('title', models.CharField(max_length=200, verbose_name='오늘의 핵심 요약')),
                ('content', models.TextField(verbose_name='상세 노트 및 코드 (마크다운)')),
                ('github_commit_url', models.URLField(blank=True, null=True, verbose_name='관련 커밋 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
