# Generated by Django 6.1 on 2026-08-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_study_class_team_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='단계 종료일'),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='단계 시작일'),
        ),
    ]
