# Generated by Django 6.1 on 2026-08-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectstage_end_date_projectstage_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmemo',
            name='block',
        ),
        migrations.AddField(
            model_name='projectmemo',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='projects.file'),
        ),
        migrations.AddField(
            model_name='projectmemo',
            name='is_request',
            field=models.BooleanField(default=False, verbose_name='수정 요청 여부'),
        ),
        migrations.AddField(
            model_name='projectmemo',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='해결 여부'),
        ),
        migrations.AddField(
            model_name='projectmemo',
            name='target_line',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='지정된 코드 라인'),
        ),
    ]
